apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: domaindata
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /DomainData/GetAll/*
        backend:
          serviceName: domainapi
          servicePort: 80